## static_countries
UPDATE static_countries SET cn_short_pt_br='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_pt_br='Emirados Árabes Unidos' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_pt_br='Afeganistão' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_pt_br='Antígua e Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_pt_br='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_pt_br='Albânia' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_pt_br='Armênia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_pt_br='Antilhas Neerlandesas' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_pt_br='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_pt_br='Antártica' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_pt_br='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_pt_br='Samoa Americana' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_pt_br='Áustria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_pt_br='Austrália' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_pt_br='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_pt_br='Azerbaijão' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_pt_br='Bósnia Herzegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_pt_br='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_pt_br='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_pt_br='Bélgica' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_pt_br='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_pt_br='Bulgária' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_pt_br='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_pt_br='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_pt_br='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_pt_br='Bermudas' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_pt_br='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_pt_br='Bolívia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_pt_br='Brasil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_pt_br='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_pt_br='Butão' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_pt_br='Ilha Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_pt_br='Botsuana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_pt_br='Bielorrússia' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_pt_br='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_pt_br='Canadá' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_pt_br='Ilhas Cocos' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_pt_br='Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_pt_br='República Centro-Africana' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_pt_br='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_pt_br='Suíça' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_pt_br='Costa do Marfim' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_pt_br='Ilhas Cocos' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_pt_br='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_pt_br='Camarões' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_pt_br='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_pt_br='Colômbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_pt_br='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_pt_br='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_pt_br='Cabo Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_pt_br='Ilha de Natal' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_pt_br='Chipre' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_pt_br='República Tcheca' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_pt_br='Alemanha' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_pt_br='Djibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_pt_br='Dinamarca' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_pt_br='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_pt_br='República Dominicana' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_pt_br='Algéria' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_pt_br='Equador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_pt_br='Estônia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_pt_br='Egito' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_pt_br='Saara Ocidental' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_pt_br='Eritreia' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_pt_br='Espanha' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_pt_br='Etiópia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_pt_br='Finlândia' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_pt_br='República de Fíji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_pt_br='Ilhas Falkland' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_pt_br='Micronésia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_pt_br='Ilhas Faroé' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_pt_br='França' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_pt_br='Gabão' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_pt_br='Reino Unido' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_pt_br='Granada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_pt_br='Geórgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_pt_br='Guiana Francesa' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_pt_br='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_pt_br='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_pt_br='Groenlândia' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_pt_br='Gâmbia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_pt_br='Guiné' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_pt_br='Guadalupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_pt_br='Guiné Equatorial' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_pt_br='Grécia' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_pt_br='Ilhas Geórgia do Sul e Sandwich do Sul' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_pt_br='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_pt_br='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_pt_br='Guiné Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_pt_br='Guiana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_pt_br='Região Administrativa Especial de Hong Kong da República Popular da China' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_pt_br='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_pt_br='Croácia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_pt_br='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_pt_br='Hungria' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_pt_br='Indonésia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_pt_br='Irlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_pt_br='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_pt_br='Índia' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_pt_br='Território Britânico do Oceano Índico' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_pt_br='Iraque' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_pt_br='Irã' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_pt_br='Islândia' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_pt_br='Itália' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_pt_br='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_pt_br='Jordânia' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_pt_br='Japão' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_pt_br='Quênia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_pt_br='Quiriquistão' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_pt_br='Camboja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_pt_br='Quiribáti' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_pt_br='Comores' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_pt_br='Federação de São Cristóvão e Neves' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_pt_br='Coreia do Norte' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_pt_br='República da Coreia' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_pt_br='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_pt_br='Ilhas Caimão' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_pt_br='Cazaquistão' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_pt_br='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_pt_br='Líbano' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_pt_br='Santa Lúcia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_pt_br='Listenstaine ' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_pt_br='Sri Lanca' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_pt_br='Libéria' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_pt_br='Lesoto' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_pt_br='Lituânia' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_pt_br='Luxemburgo' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_pt_br='Letônia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_pt_br='Líbia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_pt_br='Marrocos' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_pt_br='Mônaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_pt_br='Moldávia' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_pt_br='Madagascar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_pt_br='Ilhas Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_pt_br='Macedônia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_pt_br='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_pt_br='Mianmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_pt_br='Mongólia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_pt_br='Região Administrativa Especial de Macau da República Popular da China' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_pt_br='Ilhas Marianas do Norte' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_pt_br='Martinica' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_pt_br='Mauritânia' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_pt_br='Monserrate' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_pt_br='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_pt_br='Mauritânia' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_pt_br='Maldivas' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_pt_br='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_pt_br='México' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_pt_br='Malásia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_pt_br='Moçambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_pt_br='Namíbia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_pt_br='Nova Caledônia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_pt_br='Nigéria' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_pt_br='Ilhas Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_pt_br='Nigéria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_pt_br='Nicarágua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_pt_br='Países Baixos' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_pt_br='Noruega' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_pt_br='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_pt_br='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_pt_br='Niuê' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_pt_br='Nova Zelândia' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_pt_br='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_pt_br='Panamá' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_pt_br='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_pt_br='Polinésia Francesa' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_pt_br='Papua Nova Guiné' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_pt_br='Filipinas' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_pt_br='Paquistão' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_pt_br='Polônia' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_pt_br='São Pedro e Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_pt_br='Ilhas Picárnia' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_pt_br='Porto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_pt_br='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_pt_br='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_pt_br='Paraguai' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_pt_br='Catar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_pt_br='Reunião' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_pt_br='Romênia' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_pt_br='Rússia' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_pt_br='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_pt_br='Arábia Saudita' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_pt_br='Ilhas Salomão' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_pt_br='Seicheles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_pt_br='Sudão' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_pt_br='Suécia' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_pt_br='Singapura' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_pt_br='Santa Helena, Ascensão e Tristão da Cunha' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_pt_br='Eslovênia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_pt_br='Svalbard e Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_pt_br='Eslováquia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_pt_br='Serra Leoa' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_pt_br='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_pt_br='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_pt_br='Somália' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_pt_br='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_pt_br='São Tomé e Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_pt_br='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_pt_br='Síria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_pt_br='Suazilândia' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_pt_br='Ilhas Turcas e Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_pt_br='Chade' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_pt_br='Terras Austrais e Antárticas Francesas' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_pt_br='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_pt_br='Tailândia' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_pt_br='Tadjiquistão' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_pt_br='Toquelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_pt_br='Turcomenistão' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_pt_br='Tunísia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_pt_br='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_pt_br='Timor Leste' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_pt_br='Turquia' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_pt_br='Trinidad e Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_pt_br='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_pt_br='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_pt_br='Tanzânia' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_pt_br='Ucrânia' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_pt_br='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_pt_br='Ilhas Menores Distantes dos Estados Unidos' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_pt_br='Estados Unidos' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_pt_br='Uruguai' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_pt_br='Uzbequistão' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_pt_br='Cidade do Vaticano' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_pt_br='São Vicente e Granadinas' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_pt_br='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_pt_br='Ilhas Virgens Britânicas' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_pt_br='Ilhas Virgens Americanas' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_pt_br='Vietnã' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_pt_br='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_pt_br='Wallis e Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_pt_br='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_pt_br='Iêmen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_pt_br='Maiote' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_pt_br='África do Sul' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_pt_br='Zâmbia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_pt_br='Zimbábue' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_pt_br='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_pt_br='Sérvia e Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_pt_br='Ilhas Alanda' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_pt_br='A Ilha Heard e as Ilhas McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_pt_br='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_pt_br='Sérvia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_pt_br='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_pt_br='Guernesey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_pt_br='Ilha de Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_pt_br='São Martinho' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_pt_br='Coletividade de São Bartolomeu' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_pt_br='Países Baixos Caribenhos' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_pt_br='Curaçau' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_pt_br='São Martinho' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_pt_br='Sudão do Sul' WHERE cn_iso_2='SS';