## static_countries
UPDATE static_countries SET cn_short_pt_BR='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_pt_BR='Emirados Árabes Unidos' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_pt_BR='Afeganistão' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_pt_BR='Antígua e Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_pt_BR='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_pt_BR='Albânia' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_pt_BR='Armênia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_pt_BR='Antilhas Neerlandesas' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_pt_BR='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_pt_BR='Antártica' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_pt_BR='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_pt_BR='Samoa Americana' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_pt_BR='Áustria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_pt_BR='Austrália' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_pt_BR='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_pt_BR='Azerbaijão' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_pt_BR='Bósnia Herzegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_pt_BR='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_pt_BR='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_pt_BR='Bélgica' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_pt_BR='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_pt_BR='Bulgária' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_pt_BR='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_pt_BR='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_pt_BR='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_pt_BR='Bermudas' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_pt_BR='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_pt_BR='Bolívia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_pt_BR='Brasil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_pt_BR='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_pt_BR='Butão' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_pt_BR='Ilha Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_pt_BR='Botsuana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_pt_BR='Bielorrússia' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_pt_BR='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_pt_BR='Canadá' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Cocos' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_pt_BR='Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_pt_BR='República Centro-Africana' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_pt_BR='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_pt_BR='Suíça' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_pt_BR='Costa do Marfim' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Cocos' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_pt_BR='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_pt_BR='Camarões' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_pt_BR='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_pt_BR='Colômbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_pt_BR='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_pt_BR='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_pt_BR='Cabo Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_pt_BR='Ilha de Natal' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_pt_BR='Chipre' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_pt_BR='República Tcheca' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_pt_BR='Alemanha' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_pt_BR='Djibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_pt_BR='Dinamarca' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_pt_BR='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_pt_BR='República Dominicana' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_pt_BR='Algéria' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_pt_BR='Equador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_pt_BR='Estônia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_pt_BR='Egito' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_pt_BR='Saara Ocidental' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_pt_BR='Eritreia' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_pt_BR='Espanha' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_pt_BR='Etiópia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_pt_BR='Finlândia' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_pt_BR='República de Fíji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Falkland' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_pt_BR='Micronésia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Faroé' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_pt_BR='França' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_pt_BR='Gabão' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_pt_BR='Reino Unido' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_pt_BR='Granada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_pt_BR='Geórgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_pt_BR='Guiana Francesa' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_pt_BR='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_pt_BR='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_pt_BR='Groenlândia' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_pt_BR='Gâmbia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_pt_BR='Guiné' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_pt_BR='Guadalupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_pt_BR='Guiné Equatorial' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_pt_BR='Grécia' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Geórgia do Sul e Sandwich do Sul' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_pt_BR='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_pt_BR='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_pt_BR='Guiné Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_pt_BR='Guiana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_pt_BR='Região Administrativa Especial de Hong Kong da República Popular da China' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_pt_BR='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_pt_BR='Croácia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_pt_BR='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_pt_BR='Hungria' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_pt_BR='Indonésia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_pt_BR='Irlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_pt_BR='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_pt_BR='Índia' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_pt_BR='Território Britânico do Oceano Índico' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_pt_BR='Iraque' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_pt_BR='Irã' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_pt_BR='Islândia' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_pt_BR='Itália' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_pt_BR='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_pt_BR='Jordânia' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_pt_BR='Japão' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_pt_BR='Quênia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_pt_BR='Quiriquistão' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_pt_BR='Camboja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_pt_BR='Quiribáti' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_pt_BR='Comores' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_pt_BR='Federação de São Cristóvão e Neves' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_pt_BR='Coreia do Norte' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_pt_BR='República da Coreia' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_pt_BR='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Caimão' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_pt_BR='Cazaquistão' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_pt_BR='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_pt_BR='Líbano' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_pt_BR='Santa Lúcia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_pt_BR='Listenstaine ' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_pt_BR='Sri Lanca' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_pt_BR='Libéria' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_pt_BR='Lesoto' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_pt_BR='Lituânia' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_pt_BR='Luxemburgo' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_pt_BR='Letônia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_pt_BR='Líbia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_pt_BR='Marrocos' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_pt_BR='Mônaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_pt_BR='Moldávia' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_pt_BR='Madagascar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_pt_BR='Macedônia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_pt_BR='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_pt_BR='Mianmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_pt_BR='Mongólia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_pt_BR='Região Administrativa Especial de Macau da República Popular da China' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Marianas do Norte' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_pt_BR='Martinica' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_pt_BR='Mauritânia' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_pt_BR='Monserrate' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_pt_BR='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_pt_BR='Mauritânia' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_pt_BR='Maldivas' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_pt_BR='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_pt_BR='México' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_pt_BR='Malásia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_pt_BR='Moçambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_pt_BR='Namíbia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_pt_BR='Nova Caledônia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_pt_BR='Nigéria' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_pt_BR='Nigéria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_pt_BR='Nicarágua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_pt_BR='Países Baixos' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_pt_BR='Noruega' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_pt_BR='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_pt_BR='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_pt_BR='Niuê' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_pt_BR='Nova Zelândia' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_pt_BR='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_pt_BR='Panamá' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_pt_BR='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_pt_BR='Polinésia Francesa' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_pt_BR='Papua Nova Guiné' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_pt_BR='Filipinas' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_pt_BR='Paquistão' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_pt_BR='Polônia' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_pt_BR='São Pedro e Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Picárnia' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_pt_BR='Porto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_pt_BR='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_pt_BR='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_pt_BR='Paraguai' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_pt_BR='Catar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_pt_BR='Reunião' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_pt_BR='Romênia' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_pt_BR='Rússia' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_pt_BR='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_pt_BR='Arábia Saudita' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Salomão' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_pt_BR='Seicheles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_pt_BR='Sudão' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_pt_BR='Suécia' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_pt_BR='Singapura' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_pt_BR='Santa Helena, Ascensão e Tristão da Cunha' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_pt_BR='Eslovênia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_pt_BR='Svalbard e Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_pt_BR='Eslováquia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_pt_BR='Serra Leoa' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_pt_BR='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_pt_BR='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_pt_BR='Somália' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_pt_BR='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_pt_BR='São Tomé e Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_pt_BR='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_pt_BR='Síria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_pt_BR='Suazilândia' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Turcas e Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_pt_BR='Chade' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_pt_BR='Terras Austrais e Antárticas Francesas' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_pt_BR='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_pt_BR='Tailândia' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_pt_BR='Tadjiquistão' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_pt_BR='Toquelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_pt_BR='Turcomenistão' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_pt_BR='Tunísia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_pt_BR='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_pt_BR='Timor Leste' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_pt_BR='Turquia' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_pt_BR='Trinidad e Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_pt_BR='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_pt_BR='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_pt_BR='Tanzânia' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_pt_BR='Ucrânia' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_pt_BR='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Menores Distantes dos Estados Unidos' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_pt_BR='Estados Unidos' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_pt_BR='Uruguai' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_pt_BR='Uzbequistão' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_pt_BR='Cidade do Vaticano' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_pt_BR='São Vicente e Granadinas' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_pt_BR='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Virgens Britânicas' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Virgens Americanas' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_pt_BR='Vietnã' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_pt_BR='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_pt_BR='Wallis e Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_pt_BR='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_pt_BR='Iêmen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_pt_BR='Maiote' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_pt_BR='África do Sul' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_pt_BR='Zâmbia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_pt_BR='Zimbábue' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_pt_BR='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_pt_BR='Sérvia e Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_pt_BR='Ilhas Alanda' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_pt_BR='A Ilha Heard e as Ilhas McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_pt_BR='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_pt_BR='Sérvia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_pt_BR='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_pt_BR='Guernesey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_pt_BR='Ilha de Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_pt_BR='São Martinho' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_pt_BR='Coletividade de São Bartolomeu' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_pt_BR='Países Baixos Caribenhos' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_pt_BR='Curaçau' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_pt_BR='São Martinho' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_pt_BR='Sudão do Sul' WHERE cn_iso_2='SS';