## static_countries
UPDATE static_countries SET cn_short_ptbr='Andorra' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_ptbr='Emirados Árabes Unidos' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_ptbr='Afeganistão' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_ptbr='Antígua e Barbuda' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_ptbr='Anguilla' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_ptbr='Albânia' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_ptbr='Armênia' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_ptbr='Antilhas Neerlandesas' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_ptbr='Angola' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_ptbr='Antártica' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_ptbr='Argentina' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_ptbr='Samoa Americana' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_ptbr='Áustria' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_ptbr='Austrália' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_ptbr='Aruba' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_ptbr='Azerbaijão' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_ptbr='Bósnia Herzegovina' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_ptbr='Barbados' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_ptbr='Bangladesh' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_ptbr='Bélgica' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_ptbr='Burkina Faso' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_ptbr='Bulgária' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_ptbr='Bahrein' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_ptbr='Burundi' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_ptbr='Benin' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_ptbr='Bermudas' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_ptbr='Brunei' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_ptbr='Bolívia' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_ptbr='Brasil' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_ptbr='Bahamas' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_ptbr='Butão' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_ptbr='Ilha Bouvet' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_ptbr='Botsuana' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_ptbr='Bielorrússia' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_ptbr='Belize' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_ptbr='Canadá' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_ptbr='Ilhas Cocos' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_ptbr='Congo' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_ptbr='República Centro-Africana' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_ptbr='Congo' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_ptbr='Suíça' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_ptbr='Costa do Marfim' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_ptbr='Ilhas Cocos' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_ptbr='Chile' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_ptbr='Camarões' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_ptbr='China' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_ptbr='Colômbia' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_ptbr='Costa Rica' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_ptbr='Cuba' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_ptbr='Cabo Verde' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_ptbr='Ilha de Natal' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_ptbr='Chipre' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_ptbr='República Tcheca' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_ptbr='Alemanha' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_ptbr='Djibuti' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_ptbr='Dinamarca' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_ptbr='Dominica' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_ptbr='República Dominicana' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_ptbr='Algéria' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_ptbr='Equador' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_ptbr='Estônia' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_ptbr='Egito' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_ptbr='Saara Ocidental' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_ptbr='Eritreia' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_ptbr='Espanha' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_ptbr='Etiópia' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_ptbr='Finlândia' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_ptbr='República de Fíji' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_ptbr='Ilhas Falkland' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_ptbr='Micronésia' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_ptbr='Ilhas Faroé' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_ptbr='França' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_ptbr='Gabão' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_ptbr='Reino Unido' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_ptbr='Granada' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_ptbr='Geórgia' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_ptbr='Guiana Francesa' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_ptbr='Gana' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_ptbr='Gibraltar' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_ptbr='Groenlândia' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_ptbr='Gâmbia' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_ptbr='Guiné' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_ptbr='Guadalupe' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_ptbr='Guiné Equatorial' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_ptbr='Grécia' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_ptbr='Ilhas Geórgia do Sul e Sandwich do Sul' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_ptbr='Guatemala' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_ptbr='Guam' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_ptbr='Guiné Bissau' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_ptbr='Guiana' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_ptbr='Região Administrativa Especial de Hong Kong da República Popular da China' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_ptbr='Honduras' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_ptbr='Croácia' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_ptbr='Haiti' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_ptbr='Hungria' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_ptbr='Indonésia' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_ptbr='Irlanda' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_ptbr='Israel' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_ptbr='Índia' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_ptbr='Território Britânico do Oceano Índico' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_ptbr='Iraque' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_ptbr='Irã' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_ptbr='Islândia' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_ptbr='Itália' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_ptbr='Jamaica' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_ptbr='Jordânia' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_ptbr='Japão' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_ptbr='Quênia' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_ptbr='Quiriquistão' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_ptbr='Camboja' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_ptbr='Quiribáti' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_ptbr='Comores' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_ptbr='Federação de São Cristóvão e Neves' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_ptbr='Coreia do Norte' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_ptbr='República da Coreia' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_ptbr='Kuwait' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_ptbr='Ilhas Caimão' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_ptbr='Cazaquistão' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_ptbr='Laos' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_ptbr='Líbano' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_ptbr='Santa Lúcia' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_ptbr='Listenstaine ' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_ptbr='Sri Lanca' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_ptbr='Libéria' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_ptbr='Lesoto' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_ptbr='Lituânia' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_ptbr='Luxemburgo' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_ptbr='Letônia' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_ptbr='Líbia' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_ptbr='Marrocos' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_ptbr='Mônaco' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_ptbr='Moldávia' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_ptbr='Madagascar' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_ptbr='Ilhas Marshall' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_ptbr='Macedônia' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_ptbr='Mali' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_ptbr='Mianmar' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_ptbr='Mongólia' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_ptbr='Região Administrativa Especial de Macau da República Popular da China' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_ptbr='Ilhas Marianas do Norte' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_ptbr='Martinica' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_ptbr='Mauritânia' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_ptbr='Monserrate' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_ptbr='Malta' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_ptbr='Mauritânia' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_ptbr='Maldivas' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_ptbr='Malawi' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_ptbr='México' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_ptbr='Malásia' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_ptbr='Moçambique' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_ptbr='Namíbia' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_ptbr='Nova Caledônia' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_ptbr='Nigéria' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_ptbr='Ilhas Norfolk' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_ptbr='Nigéria' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_ptbr='Nicarágua' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_ptbr='Países Baixos' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_ptbr='Noruega' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_ptbr='Nepal' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_ptbr='Nauru' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_ptbr='Niuê' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_ptbr='Nova Zelândia' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_ptbr='Oman' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_ptbr='Panamá' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_ptbr='Peru' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_ptbr='Polinésia Francesa' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_ptbr='Papua Nova Guiné' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_ptbr='Filipinas' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_ptbr='Paquistão' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_ptbr='Polônia' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_ptbr='São Pedro e Miquelon' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_ptbr='Ilhas Picárnia' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_ptbr='Porto Rico' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_ptbr='Portugal' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_ptbr='Palau' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_ptbr='Paraguai' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_ptbr='Catar' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_ptbr='Reunião' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_ptbr='Romênia' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_ptbr='Rússia' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_ptbr='Ruanda' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_ptbr='Arábia Saudita' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_ptbr='Ilhas Salomão' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_ptbr='Seicheles' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_ptbr='Sudão' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_ptbr='Suécia' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_ptbr='Singapura' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_ptbr='Santa Helena, Ascensão e Tristão da Cunha' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_ptbr='Eslovênia' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_ptbr='Svalbard e Jan Mayen' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_ptbr='Eslováquia' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_ptbr='Serra Leoa' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_ptbr='San Marino' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_ptbr='Senegal' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_ptbr='Somália' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_ptbr='Suriname' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_ptbr='São Tomé e Príncipe' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_ptbr='El Salvador' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_ptbr='Síria' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_ptbr='Suazilândia' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_ptbr='Ilhas Turcas e Caicos' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_ptbr='Chade' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_ptbr='Terras Austrais e Antárticas Francesas' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_ptbr='Togo' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_ptbr='Tailândia' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_ptbr='Tadjiquistão' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_ptbr='Toquelau' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_ptbr='Turcomenistão' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_ptbr='Tunísia' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_ptbr='Tonga' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_ptbr='Timor Leste' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_ptbr='Turquia' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_ptbr='Trinidad e Tobago' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_ptbr='Tuvalu' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_ptbr='Taiwan' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_ptbr='Tanzânia' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_ptbr='Ucrânia' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_ptbr='Uganda' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_ptbr='Ilhas Menores Distantes dos Estados Unidos' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_ptbr='Estados Unidos' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_ptbr='Uruguai' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_ptbr='Uzbequistão' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_ptbr='Cidade do Vaticano' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_ptbr='São Vicente e Granadinas' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_ptbr='Venezuela' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_ptbr='Ilhas Virgens Britânicas' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_ptbr='Ilhas Virgens Americanas' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_ptbr='Vietnã' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_ptbr='Vanuatu' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_ptbr='Wallis e Futuna' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_ptbr='Samoa' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_ptbr='Iêmen' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_ptbr='Maiote' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_ptbr='África do Sul' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_ptbr='Zâmbia' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_ptbr='Zimbábue' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_ptbr='Palestina' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_ptbr='Sérvia e Montenegro' WHERE cn_iso_2='CS';
UPDATE static_countries SET cn_short_ptbr='Ilhas Alanda' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_ptbr='A Ilha Heard e as Ilhas McDonald' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_ptbr='Montenegro' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_ptbr='Sérvia' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_ptbr='Jersey' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_ptbr='Guernesey' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_ptbr='Ilha de Man' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_ptbr='São Martinho' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_ptbr='Coletividade de São Bartolomeu' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_ptbr='Países Baixos Caribenhos' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_ptbr='Curaçau' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_ptbr='São Martinho' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_ptbr='Sudão do Sul' WHERE cn_iso_2='SS';
